services:
    # Mandatory
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: ".env"
    privileged: true
    volumes:
      - db_data:/usr/local/mysql/var 
    networks:
        inception:
    restart: always
    init: true
    healthcheck:
      test: "mariadb-admin ping"
      interval: 5s
      timeout: 1m
      retries: 3

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: ".env"
    privileged: true
    volumes:
      - wp_data:/var/www/html
    networks:
      inception:
    restart: always
    init: true
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "8443:443"
    env_file: ".env"
    volumes:
      - wp_data:/var/www/html
    networks:
      inception:
    restart: always
    init: true
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxouvra/data/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxouvra/data/wp
