version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    env_file: ".env"
    restart: always
    init: true
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    privileged: true
    env_file: ".env"
    restart: always
    init: true
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    env_file: ".env"
    privileged: true
    restart: always
    init: true