services:
    # Mandatory
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image : mariadb
    env_file: ".env"
    volumes:
      - db_data:/var/lib/mysql 
    networks:
        inception:
    restart: always
    healthcheck:
      test: "mariadb-admin ping"
      interval: 5s
      timeout: 1m
      retries: 3

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress
    env_file: ".env"
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_data:/var/www/html
    networks:
      inception:
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    env_file: ".env"
    volumes:
      - wp_data:/var/www/html
    networks:
      inception:
    restart: always
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxouvra/data/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maxouvra/data/wp
